name: My Python project

on:
  push:

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: install requirements.txt
        run: pip install -r requirements.txt

      - name: Pylint
        run: pylint --errors-only shop_app

      - name: Run Unittest and Coverage
        run: pytest --cov=shop_app

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: EliasDardaghani
          password: ${{ secrets.PASS }}
